# Site
name: "Testing Excellence"
title: "Testing Excellence"
description: "Site for Developers and QAs"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#url: 'https://devqa.io'
url: 'localhost:4000'
baseurl: ''
google_analytics: 'UA-141585211-1'
disqus: 'demowebsite'
mailchimp-list: 'https://mailchi.mp/3b7a1f21f2f7/devqa'
include: ["_pages"]
permalink: /:title/
lazyimages: "enabled"

# Authors
authors:
  Amir:
    name: Amir Ghahrai
    display_name: Amir
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: aghahrai@gmail.com
    web: https://www.devqa.io
    twitter: https://twitter.com/testingexcel
    description: ""
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]